### PR TITLE
Autoconfigure IPv6 address as well

### PR DESCRIPTION
**Pull request by wclarie**

### CODE REVIEW

**Comment by ajacoutot** [comment]
Hi @wclarie 
Thanks for the patch. However there're a couple of things to fix before I can integrate it:
- setting _ipv6_addr may fail if the VPC/Subnet is not IPv6 enabled; this will abort the script (set -e).
- appending to hostname.if is not good as-is; if someone wants to create an AMI based on the running instance he will end up with multiple inet6 configurations.

Not sure how to best address the second point yet.

**Comment by wclarie** [comment]
Thanks for your response.

If the VPC/Subnet does not have IPv6 enabled, the mock call to meta-data/network/interfaces/macs/${_mac}/ipv6s will simply return a 404, setting _ipv6_addr to empty string. Should not generate an error. Or am I missing something?

About the second issue: yes, I know it's a bit of a hack. The proper way to do it would be to have have a dhcp6 client in base and always start that, but that's not the case. I also could not get dhcp6c from the wide-dhcpv6 package to work (and it would require installing the package, which is not ideal.)

I see a few alternatives:
- Checking if an IPv6 address is already configured by grepping the /etc/hostname.xnf0 first, and replacing it if necessary. That way at least the address is persisted in the configuration.
- Setting the IPv6 address in ec2-init and not keep it in /etc/hostname.xnf0, since ec2-init is run at least on every boot. That would require taking the ipv6_addr call out of the meta-data/instance-id != /var/db/ec2-init condition, which may be unexpected for the user.

The first option will obviously not pick up IPv6 address changes, the second one will. Which do you prefer, or do you have any other ideas?

**Comment by wclarie** [comment]
Meh, forgot to do this pull request on a separate branch, nevermind the additional changes. I'm not very good at this Github thing.

**Comment by ajacoutot** [comment]
If you get a 404, IIRC ftp(1) will return 1.

I'm really dumb when it comes to IPv6. The main issue that I see here is that we need to get the ipv6s value and hardcode it to hostname.if. Isn't there a way for us to get that IP automatically / dynamically like a dhcp would do for IPv4?

**Comment by wclarie** [comment]
About the first issue: yes, ftp will return non-zero, but the mock() function only returns the output of ftp, not its return value. So I don't think it's a problem?

Test script, with www.google.com instead of the autoconfig, to ensure a 404:
```
#!/bin/sh

set -e

ipv6_addr()
{
    local _mac="$(mock meta-data/mac)"
    local _ipv6_addr="$(mock meta-data/network/interfaces/macs/${_mac}/ipv6s)"
    echo ${_ipv6_addr}
    if [[ -n ${_ipv6_addr} ]]; then
        /sbin/ifconfig xnf0 inet6 autoconf
        /sbin/ifconfig xnf0 inet6 ${_ipv6_addr}
        print -- "rtsol\ninet6 ${_ipv6_addr}" >>/etc/hostname.xnf0
    fi
}

mock()
{
    [[ -n ${1} ]]
    local _ret
    _ret=$(ftp -MVo - http://www.google.com/latest/${1} 2>/dev/null)
    [[ -n ${_ret} ]] && print -- "${_ret}"
}

ipv6_addr
```

With:
```
ftp -MVo - http://www.google.com/latest/something
ftp: Error retrieving file: 404 Not Found
```

But with the test script:
```
$ ./testscript && echo "ok"

ok
```

**Comment by wclarie** [comment]
About the second issue: There is dhcp6 and it works on Amazon Linux and CentOS etc, but there is no dhcp6 client in OpenBSD base, just in the ports collection, and I can't get it to work. An alternative could be to make a really simple script that continually polls meta-data/network/interfaces/macs/${_mac}/ipv6s and updates the IP live.

**Comment by ajacoutot** [comment]
Hmm... polling would be ugly.
I need to think about this...

**Comment by wclarie** [comment]
I'll spend some more time today trying various proper dhcp6 options and report back.

**Comment by mbelop** [comment]
The other DHCPv6 client is isc-dhcp-client.  However, I do understand the desire to use WIDE DHCPv6 implementation. Matthieu Herrb has attempted to clean up that codebase: https://github.com/mherrb/dhcpv6 -- I don't know if it's packaged in OpenBSD or if it's working at the moment at all, but we'll have to resolve this for the base system eventually.

**Comment by wclarie** [comment]
In the meantime I have re-checked wide-dhcpv6, dhcpcd and isc-dhcp packages, and I can only make the last one work to get an IPv6 address in ec2. However, it cannot be run directly from hostname.xnf0 because there's a race condition with setting 'rtsol' (the equivalent of using ifconfig xnf0 inet6 autoconf), which is necessary to make the kernel listen to router announcements/solicitations. Basically if you do this in /etc/hostname.xnf0:
```
rtsol
!/usr/local/sbin/dhclient -6 xnf0
```
then the dhclient won't start because it needs the link-local IPv6 address first, and it may take a few seconds to 'discover' it. So you'd need a separate script to do
```
/sbin/ifconfig xnf0 inet6 autoconf
sleep 5
/usr/local/sbin/dhclient -6 xnf0
```
which is quite messy.

So the conclusion is: OpenBSD should really have an IPv6-enabled dhclient that takes care of these things properly, otherwise any solution will be ugly.

I suggest you close the pull request. I will handle this in a user-data script instead.

(Also I haven't checked what happens when you have more than one IPv6 address assigned to the instance. Most of these things are trivial to deal with when just getting the data from http://169.254.169.254/latest/meta-data/network/interfaces/macs/${_mac}/ipv6s.)

**Comment by mbelop** [comment]
Great findings, perhaps instead of "rtsol" one could specify "inet6 eui64" to fill out the MAC-based link local address for the interface and fire up "dhclient -6" right after.

**Comment by wclarie** [comment]
Ah yes I read about that, but I haven't tried it yet. Will report back about that.

**Comment by ajacoutot** [comment]
That's a good idea. That said it would still require installing an external package so I don't think ec2-init is the place to do it: it's what user-data is for imho...
Now if we can come up with a sane way to do it, I am still open to the idea :-)
For now, closing as requested.

**Comment by wclarie** [comment]
(For reference: setting ifconfig xnf0 inet6 eui64 does not fix the race condition. It still needs a sleep.)

**Pull request closed without merging**
